spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true # 시스템아웃에 찍는다. 운영에서 사용하지 말자
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mesjpa;
    username: sa
    password:
server:
  port: 8081


decorator:
  datasource:
    p6spy:
      enable-logging: true


logging:
  level:
    org:
      hibernate:
        type: trace